# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  issues:
    exclude-files:
      - \.pb\.go$
      - \.pb\.gw\.go$
    exclude-dirs:
      - bin
      - vendor
      - var
      - tmp
      - .cache

output:
  formats: colored-line-number  # Исправлено: format, а не formats
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/mrlexus21/chat-server
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mrlexus21/chat-server)

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gofmt
    - goimports  # Исправляет импорты
    - gci        # Группирует импорты
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused
    - misspell   # Исправляет опечатки
    - nolintlint # Проверяет корректность //nolint
    - prealloc   # Оптимизирует предварительное выделение памяти
    - unconvert  # Удаляет ненужные преобразования типов
    - whitespace # Исправляет пробелы

issues:
  exclude-use-default: false
  exclude:
    - G104 # _ instead of err checks
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
